In [1]:
import numpy as np

In [2]:
# scalar arithmetic single value
# scaler is linear algebra term

In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
print(arr + 1)

[2 3 4]


In [5]:
print(arr - 2)

[-1  0  1]


In [6]:
print(arr * 3)

[3 6 9]


In [7]:
print(arr / 4)

[0.25 0.5  0.75]


In [8]:
print(arr ** 5)

[  1  32 243]


In [9]:
# vector one dim arr

In [13]:
arr = ([1.01,2.5,3.99])
print(np.sqrt(arr))
print(np.round(arr)) # nearest int
print(np.floor(arr)) # down
print(np.ceil(arr)) # up

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]


In [14]:
print(np.pi)

3.141592653589793


In [17]:
#exercise

radius = np.array([1,2,3])
print(np.pi * radius ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [21]:
# element wise arithmetic

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [25]:
# comparison opr

scores = np.array([91,55,100,73,82,64])
print(scores == 100)
print(scores >= 60) # 5 students pass
print(scores < 60) # 1 student fail

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]


In [27]:
scores = np.array([91,55,100,73,82,64])

# subscript opr
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]
