In [1]:
import numpy as np

In [2]:
# filtering refers to process of selecting elements from an array that match a given condition

In [6]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18] #bool indexing
print(teenagers)

[17 16 15]


In [8]:
print(ages) # original not affected

[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]


In [16]:
adults = ages[(ages >= 18) & (ages < 65)] 
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]


In [17]:
seniors = ages[ages >= 65]
print(seniors)

[65 99]


In [18]:
evens = ages[ages % 2 == 0]
print(evens)

[20 16 30 18 22 18 20]


In [19]:
odds = ages[ages % 2 != 0]
print(odds)

[21 17 19 65 39 15 99 19 21]


In [26]:
# where funtion to filter

adults = np.where(ages >= 18, ages, 0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
