In [1]:
import numpy as np

In [24]:
rng = np.random.default_rng(seed = 1)

print(rng.integers(1, 7)) # random no between 1 to 6
print(rng.integers(low= 1, high= 101, size = (3, 2)))

3
[[52 76]
 [96  4]
 [15 83]]


In [31]:
print(np.random.uniform(low = -1, high=1, size =3))
# uniform dist each value has equal chance of being selected

[-0.42408592 -0.3734102  -0.94293289]


In [35]:
np.random(seed=1)
print(np.random.uniform(low = -1, high=1, size =(3, 2)))

TypeError: 'module' object is not callable

In [36]:
# shuffle

In [40]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print()
rng = np.random.default_rng()
rng.shuffle(arr)
print(arr)


[1 2 3 4 5 6]

[2 4 1 6 3 5]


In [46]:
fruits = np.array(["apple", "banana", "orange", "coconut", "pineapple", "kiwi"])
fruits = rng.choice(fruits, size= (3, 3))
print(fruits)

[['pineapple' 'apple' 'apple']
 ['kiwi' 'banana' 'apple']
 ['banana' 'coconut' 'banana']]


In [49]:
a = np.arange(1, 10)
print(a)


[1 2 3 4 5 6 7 8 9]


In [50]:
# evenly spaced values
l = np.linspace(1, 10, 2)
print(l)

[ 1. 10.]
