In [1]:
import numpy as np

In [10]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

# arr[start:end:step]
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [13]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

# print(arr[0:3])
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[0:4:2])
print()
print(arr[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [20]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[::-1])
print()
print(arr[::-2])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

[[13 14 15 16]
 [ 5  6  7  8]]


In [29]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

# arr[start:end:step]

# : -> all rows

# : -> all rows column 0
print(arr[:,0])
print()
print(arr[:,1])
print()
print(arr[:,2])
print()
print(arr[:,3])


[ 1  5  9 13]

[ 2  6 10 14]

[ 3  7 11 15]

[ 4  8 12 16]


In [33]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, -1])


[ 4  8 12 16]


In [34]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [35]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, 1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [36]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, 1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [37]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [38]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, 1::2])

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [39]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [40]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[:, ::-2])

[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [43]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[0:2,0:2])

[[1 2]
 [5 6]]


In [47]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[0:2, 2:4])

[[3 4]
 [7 8]]


In [48]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[2:, 0:2])

[[ 9 10]
 [13 14]]


In [49]:
arr = np.array([[1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12], 
                [13,14,15,16]])

print(arr[2:, 2:])

[[11 12]
 [15 16]]
